// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR3Jej3a8IPejaFsVtYHhKoKADczn9B6I',
    appId: '1:54320001887:web:f5d06bae30f381ca197cea',
    messagingSenderId: '54320001887',
    projectId: 'cashier-d2878',
    authDomain: 'cashier-d2878.firebaseapp.com',
    storageBucket: 'cashier-d2878.firebasestorage.app',
    measurementId: 'G-LZQYM4K9L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBfLadQcC0dlrTNMLoyCxgKU6u50BBto4',
    appId: '1:54320001887:android:e6633233d0ec8ab5197cea',
    messagingSenderId: '54320001887',
    projectId: 'cashier-d2878',
    storageBucket: 'cashier-d2878.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR7c73vgXoS2eI44G1cPjfUGm0ESw27LA',
    appId: '1:54320001887:ios:36826283e6e82622197cea',
    messagingSenderId: '54320001887',
    projectId: 'cashier-d2878',
    storageBucket: 'cashier-d2878.firebasestorage.app',
    iosBundleId: 'com.natureship.cashier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR7c73vgXoS2eI44G1cPjfUGm0ESw27LA',
    appId: '1:54320001887:ios:36826283e6e82622197cea',
    messagingSenderId: '54320001887',
    projectId: 'cashier-d2878',
    storageBucket: 'cashier-d2878.firebasestorage.app',
    iosBundleId: 'com.natureship.cashier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR3Jej3a8IPejaFsVtYHhKoKADczn9B6I',
    appId: '1:54320001887:web:86802881c02f90da197cea',
    messagingSenderId: '54320001887',
    projectId: 'cashier-d2878',
    authDomain: 'cashier-d2878.firebaseapp.com',
    storageBucket: 'cashier-d2878.firebasestorage.app',
    measurementId: 'G-Q6PDYDX3YW',
  );
}